
spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Aniket - Developer"
    email: "ani@gmail.com"
  onCallSupport:
    - 99999999999
    - 99999999999